### ISSUE TITLE
Yaml input file support

### ISSUE THREAD

**Issue by tevariou** [rtk-incubator/rtk-query-codegen#17]
I'm using Django Rest Framework which generates openapi schema in yml format. Would it be possible to support yml file in the future?

**Comment by msutkowski** [comment]
Could you perhaps try using something like this https://github.com/tromgy/swagger-yaml-to-json-schema before running the codegen?

**Comment by msutkowski** [comment]
@tevariou  Actually, just disregard that comment. It already supports yaml. I also confirmed it generates from the same example in the readme using `.yaml` instead of `.json` for the petstore schema.

![image](https://user-images.githubusercontent.com/784953/104530415-c1e4a100-55c0-11eb-9d42-903250b7572c.png)
