### ISSUE TITLE
Bad import using --baseQuery when generated file and baseQuery file are in the same folder

### ISSUE THREAD

**Issue by tevariou** [rtk-incubator/rtk-query-codegen#32]
**Description**
Running
```shell
npx @rtk-incubator/rtk-query-codegen-openapi \
--file ./src/services/api.generated.ts \
--baseQuery ./src/services/custom-fetch-base-query.ts:customFetchBaseQuery \
--hooks \
../django/openapi-schema.yml
```
The import string at the top of `api.generated.ts` is `import { customFetchBaseQuery } from "custom-fetch-base-query";` resulting in error `TS2307: Cannot find module 'custom-fetch-base-query' or its corresponding type declarations`. 
`api.generated.ts` and `custom-fetch-base-query.ts` are in the same folder.

**Resolution**
The import string should be `import { customFetchBaseQuery } from "./custom-fetch-base-query";`

**Comment by buzzie-bee** [comment]
I have the same issue.

`Using: npx --yes @rtk-incubator/rtk-query-codegen-openapi --file ./src/redux/services/rokkup/rokkup-api.generated2.ts --exportName generatedRokkupApi --baseUrl / --baseQuery ./src/redux/services/rokkup/customBaseQuery.ts:customBaseQuery ./rokkupApiDefinition.json `

The import in the generated api is:

`import { customBaseQuery } from "customBaseQuery";`

I've dug into the code for the generator and it looks like the problem is occurring during the path.resolve function in the /src/utils/resolveImportPath.ts function.

When calling path.relative(containingFile, modulePath) and the two files are in the same folder it resolves to just the module name and doesn't add the './' to the start of the string.

I don't know enough about the codebase to know this for sure but it looks like this resolveImportPath function is only called for internal imports, and doesn't apply to module imports (like @rtk-incubator/rtk-query).

A hacky fix for now that works is to do the following:
`export function resolveImportPath(modulePath: string, containingFile: string) {
  containingFile = path.resolve(containingFile, '..');
  const strippedFile = stripFileExtension(path.relative(containingFile, modulePath));
  if (strippedFile[0] !== '.') {
    return `./${strippedFile}`;
  }
  return strippedFile;
}`

Where if the start of the file is not a . we append the stripped filename to ./ . This would only apply for modules in the same directory so it wouldn't fire for folders further up or down the folder tree. It also *shouldn't* fire when using node_modules if my assumption about resolveImportPath not being called for node_modules is accurate.

 A better check might be to do this check when processing the custom base query module to check the path, if it isn't in the node_modules folder then we know it's a file, then it would be safer to append the ./ if the end string doesn't contain one. Would involve adding a few params to a bunch of functions and I don't feel confident enough in the codebase to start doing that.
